spring.application.name=SistemaSkill Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_skill
spring.datasource.username=postgres
spring.datasource.password=v22457752

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8080
jwt.secret=SistemaSkill-JWT-Secret-2026-Projeto-Entrevista